// Re-export from the new modular API structure
// This maintains backward compatibility with existing code
export { api, ApiService } from './api/index';
export type {
  QueryData,
  BronWebsite,
  BronDocument,
  CanonicalDocument,
  CanonicalDocumentWithExtensions,
  CanonicalDocumentDraft,
  PaginationParams,
  DocumentFilterParams,
  WorkflowDocument,
  WorkflowOutput,
  Run,
  Subgraph,
  SubgraphMetadata,
  MetaGraphResponse,
  ClusterNode,
  NavigationGraphResponse,
  NavigationNode,
  GraphHealthResponse,
  GraphRAGQueryOptions,
  GraphRAGResponse,
  ExportTemplate,
  ExportFormat,
  ExportTemplateCreateInput,
  ExportTemplateUpdateInput,
  TemplateValidationResult,
  WorkflowConfiguration,
  AvailableBeleidsscanWorkflow,
  ConfigurableFeatureFlag,
  WorkflowConfigurationCreateInput,
  WorkflowConfigurationUpdateInput,
  SustainabilityMetrics,
  SustainabilityKPI,
} from './api/index';
